services:
  postgres:
    image: postgres:16
    container_name: logistics_postgres
    environment:
      POSTGRES_DB: logistics
      POSTGRES_USER: logistics
      POSTGRES_PASSWORD: logistics
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  mongo:
    image: mongo:7
    container_name: logistics_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: logistics_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:
  mongo_data:
